color: null
fieldLayouts:
  c296f3ce-a519-4fa8-b94c-31eef0d9a5ed:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-16T09:35:19+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7977fe71-ac33-47bb-a5ff-f6d196c7690f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 72137ede-76f2-484c-aa3a-23d08cb915bd
        userCondition: null
handle: category
hasTitleField: true
icon: null
name: Categorie
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
