color: null
description: null
fieldLayouts:
  70838215-b807-400a-9300-9f06f968b1c3:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-16T10:15:53+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0e4d435a-63e8-4aab-87e5-bf8db78a672c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-28T18:25:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c5371f50-6484-46d4-9a00-27051cfc9635 # Fotos (Matrix)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d45ecf58-70cd-481d-bf80-e3ebba175a36
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 681b9349-2fc9-4fc4-a974-f964ec577780
        userCondition: null
handle: pictures
hasTitleField: true
icon: null
name: "Foto's"
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
