altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  253cb58d-042b-4daf-9f62-c3529129178c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-29T12:44:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: cabdfd58-f25d-438f-a7d7-d85cd199bb69
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-16T09:30:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9ccfab1b-7fcd-4e50-9b17-9cd30330a654 # Categorie
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b15c285-6995-4025-a34f-8f052ecd0688
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f3a448a4-4756-41db-abd9-2a51c2001c31
        userCondition: null
fs: bestanden
handle: fotos
name: "Foto's"
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
