columnSuffix: null
handle: mainPicHeight
instructions: "De hoogte (in percentage) van de hoofdfoto tov de andere foto's"
name: 'Hoogte hoofdfoto'
searchable: false
settings:
  defaultValue: 50
  max: 100
  min: 0
  step: 1
  suffix: '%'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Range
