columnSuffix: null
handle: picsGoupWidth
instructions: null
name: 'Breedte fotogroep'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  step: 10
  suffix: px
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
